//
//  Data.swift
//  Project 1
//
//  Created by Minh Mon on 6/27/18.
//  Copyright © 2018 Minh Mon. All rights reserved.
//

import Foundation

class Data {
    static var qoutes = [
        ["Hãy bắt đầu làm những việc cần thiết, sau đó làm những việc bạn có thể, và tự nhiên bạn có thể làm những điều không thể", "Điều tuyệt vời nhất trên thế giới bạn không thể nhìn thấy và chạm được- bạn sẽ phải cảm nhận chúng bằng trái tim", "Tôi không thể thay đổi hướng gió, nhưng tôi có thể thay đổi con đường tôi đi để đạt được đến nơi mà tôi muốn", "Bạn phải làm những điều mà bạn nghĩ rằng mình không thể", "Hãy cố gắng trở thành cầu vồng trên đám mây của một ai đó", "Không có gì là không thể, chính từ này cũng nói lên rằng tôi có thể", "Hãy đặt trái tim, tinh thần của bạn vào những việc làm nhỏ nhất. Đó chính là bí mật của sự thành công", "Cơ hội luôn chào đón chúng ta, hãy nắm lấy nó", "Chúng ta biết chúng là là ai, nhưng chúng ta không biết những điều chúng ta có thể làm được", "Thất bại không bao giờ xảy ra nếu quyết tâm thành công của chúng ta đủ mạnh", "Những gì bạn làm hôm nay có thể cải thiện tương lai", "Để thành công, trước tiên ta phải tin là ta có thể", "Đừng nhìn lại xem bạn đã làm những gì. Hãy cứ tiếp tục đi", "Ngày mới bắt đầu với suy nghĩ mới và sức mạnh mới", "Tôi đã thất bại liên tục trong cuộc đời và đó là lí do tại sao tôi thành công", "Một người sáng tạo luôn bị thôi thúc bởi khát vọng của sự thành công, chứ không phải khát vọng đánh bại người khác", "Luôn cố gắng hết sức thực hiện kế hoạch của bạn, bạn sẽ gặp hái thành công sau này", "Khát vọng chiến thắng, khát vọng của thành công, khát vọng chạm đến khả năng của bạn...đây là những nhân tố làm bạn trở thành người xuất sắc", "Bạn không bao giờ quá già để thiết lập một mục tiêu mới hay để mơ một giấc mơ mới"],
        ["Cuộc sống không phải là một vấn đề cần giải quyết, mà là thực tế để chúng ta cần trải nghiệm", "Điều quan trọng nhất để tận hưởng cuộc sống của chúng ta là hãy luôn hạnh phúc", "Cuộc sống không phải là đi tìm con người thật của bạn. Cuộc sống tạo ra bản thân bạn", "Cuộc sống này thực sự đơn giản, nhưng chúng ta luôn làm nó trở nên phức tạp", "Chúng ta không thể nhớ những ngày đã qua, nhưng chúng ta có thể nhớ những khoảnh khắc", "Cuộc sống hạnh phúc thật đơn giản, tất cả điều phụ thuộc vào bạn, tùy thuộc vào cách bạn suy nghĩ", "Cuộc sống là giấc mơ đối với những người ngôn ngoan, là cuộc chơi với những người khờ dại, là hài kịch đối với những người giàu, là bi kịch đối với những người nghèo", "Cuộc sống được đánh giá không phải bằng số năm bạn sống mà là cách bạn sống trong những năm đó", "Cuộc sống là những thông điệp", "Hãy quay về hướng mặt trời, và bạn sẽ không thấy bóng tối", "Hãy tìm đến nơi có niềm vui, bởi niềm vui có thể xóa đi những đau khổ", "Khi bạn thay thế những suy nghĩ tiêu cực bằng suy nghĩ tích cực, bạn sẽ nhận được những kết quả tích cực", "Có một điều mà chúng ta có thể làm được tốt hơn bất kì ai khác: chúng ta có thể là chính mình", "Ngày hôm qua chúng ta không thể lấy lại, nhưng ngày hôm nay là ngày chúng ta có thể chiến thắng hoặc thất bại", "Hãy tin rằng cuộc sống này đáng để chúng ta sống và sự tin tưởng của bạn có thể giúp tạo ra sự thật"],
        ["Bạn không tìm kiếm tình yêu, mà là tình yêu tìm đến bạn", "Khi gặp nhau hãy bắt đầu bằng một nụ cười, bởi nụ cười là sự khỏi đầu của tình yêu", "Tình yêu thực sự giống như những con ma, mọi người đều bàn luận đến chúng nhưng rất ít người có thể nhìn thấy", "Người không trưởng thành sẽ nói rằng: “ Anh yêu em bởi vì anh cần em” Nhưng người trưởng thành sẽ nói rằng “ Anh cần em bởi anh yêu em", "Đôi khi trái tim có thể nhìn thấy những điều mà đôi mắt không thể thấy được", "Điều tuyệt vời nhất cần nắm giữ trong cuộc sống này đó là tình yêu", "Hoa không thể nở nếu không có ánh sáng mặt trời, và con người không thể sống nếu thiếu tình yêu", "Tôi tìm ra một nghịch lí rằng, nếu bạn yêu sâu sắc đến mức đau đớn, sẽ chẳng thể nào đau đớn hơn nữa, chỉ có thêm tình yêu mà thôi", "Nếu cuộc sống thiếu đi tình yêu giống như một khu vườn với những bông hoa héo", "Âm thanh hay nhất trong cuộc sống đó chính là giọng nói của người phụ nữ chúng ta yêu"]
    ]
}
